server:
  port: 3001
  name: ZurichTech
  version: 1.0.0

db:
  uri: mongodb+srv://admin:pramod1234@poc-projects-cluster.bd8rbrv.mongodb.net/zurich-tech?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=true

oauth:
  google:
    client_id: 743963550656-kuvhqrgkaj8sd6bkhtqealk8sek8v50r.apps.googleusercontent.com
    client_secret: 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
    redirect_uri: /auth/redirect
    client_url: http://localhost:3000

reqres:
  api: https://reqres.in/api