# Unit Test AWS CDK infrastructure
name: Run AWS CDK Unit Test
on: 
  push:
    branches:
      - master
      - main
      - dev
   
jobs:
  run:
    name: Run AWS CDK Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Unit Testing
        run: |
          cd aws
          npm ci
          npm run test:cov
          rm -rf coverage
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Pramod AJ
          author_email: avj2352@gmail.com
          message: 'Updating Test Coverage'
          add: '*'
